version: '3.9'

services:
  clickhouse:
    image: yandex/clickhouse-server:21.8.12
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/clickhouse/data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "wget", "-q", "http://127.0.0.1:8123/ping"]

  api:
    restart: always
    build:
      context: .
    command: gunicorn3 --reuse-port ooniapi.wsgi -b 0.0.0.0:8000
    volumes:
      - ./newapi/:/app
    ports:
      - "8000:8000"
    depends_on:
      clickhouse:
        condition: service_healthy
