version: '3.9'

services:
  db:
    image: postgres:11.12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: oonitest
      POSTGRES_PASSWORD: test
      POSTGRES_DB: oonitestdb
    healthcheck:
      test: ["CMD", "pg_isready"]

  api:
    restart: always
    build:
      context: .
    command: gunicorn3 --reuse-port ooniapi.wsgi -b 0.0.0.0:8000
    volumes:
      - ./newapi/:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
