version: '3.9'

services:
  clickhouse:
    image: yandex/clickhouse-server:21.8.12
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/clickhouse/data:/var/lib/clickhouse

  api:
    restart: always
    build:
      context: .
    command: gunicorn3 --reuse-port ooniapi.wsgi --statsd-host 127.0.0.1:8125
    volumes:
      - ./newapi/:/app
    ports:
      - "8000:8000"
    depends_on:
      - clickhouse
