version: '3.9'

services:
  db:
    image: postgres:11.12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: oonitest
      POSTGRES_PASSWORD: test
      POSTGRES_DB: oonitestdb
    volumes:
      # ssh ams-pg.ooni.org -t pg_dump metadb -U shovel --schema-only > scripts/2_metadb_schema.sql
      - ./newapi/tests/integ/1_metadb_users.sql:/docker-entrypoint-initdb.d/1_metadb_users.sql
      - ./newapi/tests/integ/2_metadb_schema.sql:/docker-entrypoint-initdb.d/2_metadb_schema.sql
      - ./newapi/tests/integ/3_test_fixtures.sql:/docker-entrypoint-initdb.d/3_test_fixtures.sql

  clickhouse:
    image: yandex/clickhouse-server:21.8.8
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/clickhouse/data:/var/lib/clickhouse

  api:
    restart: always
    build:
      context: .
    command: gunicorn3 --reuse-port ooniapi.wsgi --statsd-host 127.0.0.1:8125
    volumes:
      - ./newapi/:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - clickhouse
