name: OONI API local tests
on:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - name: Run integ tests
        # Uses Dockerfile ./build_runner.sh and docker-compose.yml to set up the runner
        run: |
          docker-compose run --rm api \
            pytest-3 -vv --cov=ooniapi \
              --create-db \
              tests/functional/test_private_explorer.py \
              tests/integ/test_aggregation.py \
              tests/integ/test_citizenlab.py \
              tests/integ/test_integration.py \
              tests/integ/test_integration_auth.py \
              tests/integ/test_prioritization.py \
              tests/integ/test_private_api.py \
              tests/integ/test_probe_services.py \
              tests/unit/test_prio.py
              #tests/integ/test_prioritization_nodb.py \
              #tests/integ/test_probe_services_nodb.py \
              #tests/integ/test_integration_auth.py \

      - name: debug docker
        if: always()
        run: docker logs api_db_1

      - name: debug docker
        if: always()
        run: docker ps -a
