name: OONI API local tests
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - name: Run integ tests
        run: |
          docker-compose run --rm api \
            pytest-3 --show-capture=no -s -vv --cov=ooniapi \
              --create-db \
              tests/integ/test_aggregation.py \
              tests/integ/test_citizenlab.py \
              tests/integ/test_integration.py \
              tests/integ/test_integration_auth.py \
              tests/integ/test_prioritization_nodb.py \
              tests/integ/test_probe_services_nodb.py
      - name: debug docker
        if: always()
        run: docker logs api_db_1

      - name: debug docker
        if: always()
        run: docker ps -a
