name: OONI API local tests
on:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true


      - name: Build docker image
        run: make build

      - name: Setup database fixtures
        run: make initdb

      - name: Run all tests
        run: T="--show-capture=no -s -vv --cov=ooniapi" make tests

      - name: debug docker
        if: always()
        run: docker ps -a
